### ISSUE TITLE
The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by Smile42RU** [RocketMod/Rocket#723]
This server will automatically save every 1800 seconds
Error while compiling generated serializer
/tmp/67854194/40dd2002.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.2.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /game/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)

root@ubuntu:/game# uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

root@ubuntu:/game# mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by Smile42RU** [comment]
@fr34kyn01535 need ASAP response, we are support team at beastgaming.club (beastgaming.space - beta english) and we have a lot of clients with same issue.

We can provide you any needed answers or just create server with this typically environment and not working Rocketmod.

Thanks.

**Comment by fr34kyn01535** [comment]
Please, install a new server, download latest rocket and install it without any plugins. Make sure you overwrote all dlls, Rocket.API.dll, Rocket.Core.dll and Rocket.Unturned.dll! All plugins need an update due to a breaking change.

**Comment by Smile42RU** [comment]
Not closed. New server. New app installed from Steam. New Rocket overwritten over original server files (1 .exe; 4 dll). Not worked for us.

How i can see, @Diablosito33 still have same issue: https://github.com/RocketMod/Rocket/issues/712

**Comment by Diablosito33** [comment]
Correct, I did changed **dlls from managed** folder and **added rocketlaun.exe on correct folder**, it just still there, should I try format my os? It is unbuntu 14.04 too.

**Comment by Smile42RU** [comment]
@Diablosito33 okay, nice, if you can fix it and describe how and if u want i can provide you free 4 GB RAM / 2 Core CPU VM for one month as community gift from https://beastgaming.space :)

**Comment by Diablosito33** [comment]
I was about to try on my machine. i would need to backup my server and website. How canI get that vm? It would be amazing for me. (I'll blow with it!!).

**Comment by fr34kyn01535** [comment]
Smile42RU do you have teamspeak? Connect to rocketmod.net and give me access to a vm where you tried, going to look over it...

**Comment by Smile42RU** [comment]
Solved in new build.
Thank you @fr34kyn01535 for help!

**Comment by Diablosito33** [comment]
Just tried to change the files with new build, bug stills.
I'll try a fresh install.
Thanks for the warning of new build.

**Comment by Smile42RU** [comment]
As we understand this issue just log messaging, nothing important, just skip.
We'll test it on our VM's in next few hours.

**Comment by Diablosito33** [comment]
ok thanks :)
When I try help (command) at server, it only tells me the [VANILLA] ones,
then I try to use rocket commands and they dont work, the "PERMISSION" seems not working after that, I tried to add myself simply to VIP and chat colors doesn't work, not even "compass" for example, works, but strangely I guess "P" command, for example, works.
I'll try to understand what works and what doesn't. I'll update u with that in a few hours.

**Comment by brieyla1** [comment]
i just tyied the new build, and i still have the exact same error ... any help ? (i have teamspeak)

**Comment by Diablosito33** [comment]
It is affecting ur server?
Like rocket is not working? Server isn't at master list?

**Comment by brieyla1** [comment]
i mean just not appearing on masterserver, i also tryied to connect via IP, but no chance... that's 2 days and still did nothing

**Comment by Smile42RU** [comment]
@fr34kyn01535 okay, i think we need go back to this issue. We tried everything and check everything from network and forwarding to iptables and encodings, but:

1. Server not showing up in servers lists (ports opened, we are sure)
2. Rocket.API.IDefaultable still happens

And i've found one else man with same issue: https://rocketmod.net/viewtopic.php?f=45&t=2108

P.S. Now, i have VM for tests with public IP without NAT.
Call me any time.

P.P.S I know, it may be annoying, but i want just solve issue with servers list and i see same troubles around me on forums and github issues. Sorry for inconvenience.

**Comment by Smile42RU** [comment]
Tested twice with @fr34kyn01535, now. It's NOT Rocket issue. 
Some shit with servers list happens with vanilla server too.

I have not any additional questions and going rebuild all environment including steamcmd and other stuff. But, definitely, it's not a Rocket issue.

**Comment by AnonymousMW3** [comment]
I have this error guys:

[Code]
Error while compiling generated serializer
/tmp/f0614e7/13643916.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.3.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /var/www/clients/client6/web34/home/unturneditaroleplay/unturnedrp/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)
[/Code]

**Comment by bartezr8** [comment]
I have setup everything on the new fresh server and got same error:
```
/tmp/160d8daf/11a6150b.cs(27,36) : error CS0012: The type `Rocket.API.IDefaultable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Rocket.API, Version=2.6.4.0, Culture=neutral, PublicKeyToken=null'
(0,0) : error : /home/unt/unturned/Unturned_Headless_Data/Managed/Rocket.Core.dll (Location of the symbol related to previous error)

```

**Comment by planeguy98765** [comment]
I have the same error. I am now currently removing mono-runtime and mono-complete.

**Comment by saran-k** [comment]
Is this issue have been solved for you guys? I got the same error using rocketmod 710 build with ubuntu14.05. #840

**Comment by Smile42RU** [comment]
@saran-k Nope. But you may just skip it, nothing serious happens.
